kubectl delete ingress ingress-service
kubectl delete svc myfrontend-service
kubectl delete deploy my-frontend-deployment
kubectl delete svc mybackend-service
kubectl delete deploy my-backend-deployment
kubectl delete svc my-postgres-service
kubectl delete deploy my-postgres-deployment
kubectl delete secret my-postgres-secret
kubectl delete pvc my-postgres-pvc
kubectl delete svc my-redis-service
kubectl delete deploy my-redis-deployment
kubectl delete configmap my-app-configmap